### ISSUE TITLE
Where is source code of gui part?

### ISSUE THREAD

**Issue by bookvik** [mikub/titanoboa-gui#1]

**Comment by mikub** [comment]
Hi @bookvik, 
the gui part is not OSSed yet, this repo is basically just its source cljs code compiled into js - which might still be useful e.g. when manually building t-boa: 
https://github.com/mikub/titanoboa/wiki/Building-from-the-repository

Cheers
Miro

**Comment by bookvik** [comment]
Thanks. this is still a very cool system despite the fact that in some places "ossless" =)
